### ISSUE TITLE
cpio broken in Makefile

### ISSUE THREAD

**Issue by nootkroot** [Myldero/kernelinit#1]
With the current Makefile, I run into this error:

`` cpio: cannot change to directory `kernelinit': No such file or directory` ``

This is because the `-D` option for `cpio` expects an absolute path. An easy fix for this is to replace `-D kernelinit` with `-D $(PWD)/kernelinit`.

**Comment by Myldero** [comment]
Works fine on my system, but it's an easy fix, so I've gone ahead and fixed it :)
